server:
  port: 8092

spring:
  application:
    name: CLOUDDEMO-CONSUMER
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

  main:
    allow-circular-references: true

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"